<?php

namespace AppBundle\Repository;

/**
 * ActivityLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityLogRepository extends \Doctrine\ORM\EntityRepository
{
    public function findActivityByFilter($filters){
        $qb = $this->createQueryBuilder('a');
        if(isset($filters['entite']) and $filters['entite']!=''){
            $qb->join('a.user','u')
            ->join('u.entite','e')
            ->where('e.id=:entiteId')
            ->setParameter('entiteId',$filters['entite']);
        }
        if((isset($filters['dateDeb']) && $filters['dateDeb']!='')){
            $qb->andWhere('a.createdAt BETWEEN :start AND :end')
            ->setParameter('start',$filters['dateDeb'])
            ->setParameter('end',$filters['dateFin']);
        }
        $qb->orderBy('a.createdAt','desc');
        // return $qb->getQuery()->getResult();
        return $qb->getQuery();

    }
    public function checkImportDid($filter){
        $qb = $this->createQueryBuilder('a');
        $qb->join('a.user','u')
        ->join('u.entite','e')
        ->where('e.id=:entiteId')
        ->andWhere('a.success =:success')
        ->andWhere('a.createdAt BETWEEN :start AND :end')
        ->setParameter('entiteId',$filter['entiteId'])
        ->setParameter('success',true)
        ->setParameter('start',$filter['dateDeb'])
        ->setParameter('end',$filter['dateFin']);
        return $qb->getQuery()->getResult();
    }
}
