<?php

namespace AppBundle\Repository;

/**
 * CarouselRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarouselRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSlideByOrder(){
        $qb = $this->createQueryBuilder('c')
        ->addOrderBy('c.ordre','ASC');
        return $qb->getQuery()->getResult();
    }
}
