<?php

namespace AppBundle\Repository;

/**
 * CisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CisRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * exportVoyageur
     *
     * @return type
     */
    public function exportVoyageur($dateDeb, $dateFin, $selStatus)
    {
        if (($dateDeb=="")&&($dateFin=="")&&($selStatus==-1)){
            $dql = " SELECT ci
            FROM AppBundle:Cis ci
                    ";
            $query = $this->_em->createQuery($dql);
            $result = $query->getResult();
            return $result;
        } elseif (($dateDeb!="")&&($dateFin!="")&&($selStatus==-1)){
            $dql = " SELECT ci
            FROM AppBundle:Cis ci
            WHERE ci.createdAt BETWEEN :start AND :end ";
            $datetime = new \DateTime();
            $dateStart = $datetime->createFromFormat('d/m/Y', $dateDeb);
            $datetime2 = new \DateTime();
            $dateEnd = $datetime2->createFromFormat('d/m/Y', $dateFin);
            $query = $this->_em->createQuery($dql)
                ->setParameter('start',$dateStart->format('Y-m-d').'%')
                ->setParameter('end',$dateEnd->format('Y-m-d').'%');
            $result = $query->getResult();
            return $result;
        } elseif (($dateDeb=="")&&($dateFin=="")&&($selStatus==0)){
            $dql = " SELECT ci
            FROM AppBundle:Cis ci
            WHERE ci.status = 0";
            $query = $this->_em->createQuery($dql);
            $result = $query->getResult();
            return $result;
        } elseif (($dateDeb=="")&&($dateFin=="")&&($selStatus==1)){
            $dql = " SELECT ci
            FROM AppBundle:Cis ci
            WHERE ci.status = 1";
            $query = $this->_em->createQuery($dql);
            $result = $query->getResult();
            return $result;
        } elseif (($dateDeb!="")&&($dateFin!="")&&($selStatus==0)){
            $dql = " SELECT ci
            FROM AppBundle:Cis ci
            WHERE ci.status = 0
             AND ci.createdAt BETWEEN :start AND :end ";
            $datetime = new \DateTime();
            $dateStart = $datetime->createFromFormat('d/m/Y', $dateDeb);
            $datetime2 = new \DateTime();
            $dateEnd = $datetime2->createFromFormat('d/m/Y', $dateFin);
            $query = $this->_em->createQuery($dql)
                ->setParameter('start',$dateStart->format('Y-m-d').'%')
                ->setParameter('end',$dateEnd->format('Y-m-d').'%');
            $result = $query->getResult();
            return $result;
        }  elseif (($dateDeb!="")&&($dateFin!="")&&($selStatus==1)){
            $dql = " SELECT ci
            FROM AppBundle:Cis ci
            WHERE ci.status = 1
             AND ci.createdAt BETWEEN :start AND :end ";
            $datetime = new \DateTime();
            $dateStart = $datetime->createFromFormat('d/m/Y', $dateDeb);
            $datetime2 = new \DateTime();
            $dateEnd = $datetime2->createFromFormat('d/m/Y', $dateFin);
            $query = $this->_em->createQuery($dql)
                ->setParameter('start',$dateStart->format('Y-m-d').'%')
                ->setParameter('end',$dateEnd->format('Y-m-d').'%');
            $result = $query->getResult();
            return $result;
        }
        else {
            return -2;
        }
    }

    public function findByFilter(){
        $qb = $this->createQueryBuilder('c');
        return $qb->getQuery();
    }
}
