<?php

namespace AppBundle\Repository;

/**
 * DvsseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DvsseRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * exportEpidemie
     *
     * @return type
     */
    public function exportEpidemie($dateDeb, $dateFin, $selNiveau)
    {
        if (($dateDeb=="")&&($dateFin=="")&&($selNiveau==-1)){
            $dql = " SELECT dv
            FROM AppBundle:Dvsse dv
                    ";
            $query = $this->_em->createQuery($dql);
            $result = $query->getResult();
            return $result;
        } elseif (($dateDeb!="")&&($dateFin!="")&&($selNiveau==-1)){
            $dql = " SELECT dv
            FROM AppBundle:Dvsse dv
            WHERE dv.createdAt BETWEEN :start AND :end ";
            $datetime = new \DateTime();
            $dateStart = $datetime->createFromFormat('d/m/Y', $dateDeb);
            $datetime2 = new \DateTime();
            $dateEnd = $datetime2->createFromFormat('d/m/Y', $dateFin);
            $query = $this->_em->createQuery($dql)
                ->setParameter('start',$dateStart->format('Y-m-d').'%')
                ->setParameter('end',$dateEnd->format('Y-m-d').'%');
            $result = $query->getResult();
            return $result;
        } elseif (($dateDeb=="")&&($dateFin=="")&&($selNiveau==0)){
            $dql = " SELECT dv
            FROM AppBundle:Dvsse dv
            WHERE dv.pays = 'MG'";
            $query = $this->_em->createQuery($dql);
            $result = $query->getResult();
            return $result;
        } elseif (($dateDeb=="")&&($dateFin=="")&&($selNiveau==1)){
            $dql = " SELECT dv
            FROM AppBundle:Dvsse dv
            WHERE dv.pays != 'MG'";
            $query = $this->_em->createQuery($dql);
            $result = $query->getResult();
            return $result;
        } elseif (($dateDeb!="")&&($dateFin!="")&&($selNiveau==0)){
            $dql = " SELECT dv
            FROM AppBundle:Dvsse dv
            WHERE dv.pays = 'MG'
             AND dv.createdAt BETWEEN :start AND :end ";
            $datetime = new \DateTime();
            $dateStart = $datetime->createFromFormat('d/m/Y', $dateDeb);
            $datetime2 = new \DateTime();
            $dateEnd = $datetime2->createFromFormat('d/m/Y', $dateFin);
            $query = $this->_em->createQuery($dql)
                ->setParameter('start',$dateStart->format('Y-m-d').'%')
                ->setParameter('end',$dateEnd->format('Y-m-d').'%');
            $result = $query->getResult();
            return $result;
        }  elseif (($dateDeb!="")&&($dateFin!="")&&($selNiveau==1)){
            $dql = " SELECT dv
            FROM AppBundle:Dvsse dv
            WHERE dv.pays != 'MG'
             AND dv.createdAt BETWEEN :start AND :end ";
            $datetime = new \DateTime();
            $dateStart = $datetime->createFromFormat('d/m/Y', $dateDeb);
            $datetime2 = new \DateTime();
            $dateEnd = $datetime2->createFromFormat('d/m/Y', $dateFin);
            $query = $this->_em->createQuery($dql)
                ->setParameter('start',$dateStart->format('Y-m-d').'%')
                ->setParameter('end',$dateEnd->format('Y-m-d').'%');
            $result = $query->getResult();
            return $result;
        }
        else {
            return -2;
        }
    }
}
