<?php

namespace AppBundle\Repository;

/**
 * EntiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntiteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEntiteWithoutMe($user){
        $qb = $this->createQueryBuilder('e');
        $qb->where('e.id !=:userEntiteId')
        ->setParameter('userEntiteId',$user->getEntite()->getId());
        return $qb->getQuery()->getResult();
    }
    public function findEntiteWithoutMeQuery($user){
        $qb = $this->createQueryBuilder('e');
        $qb->where('e.id !=:userEntiteId')
        ->setParameter('userEntiteId',$user->getEntite()->getId());
        return $qb;
    }
}
