<?php

namespace AppBundle\Repository;

/**
 * MpanisaVisitorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MpanisaVisitorRepository extends \Doctrine\ORM\EntityRepository
{
}
