<?php

namespace AppBundle\Repository;

/**
 * VeliranoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VeliranoRepository extends \Doctrine\ORM\EntityRepository
{
}
